---
- name: Add GitLab Runner repository
  ansible.builtin.shell:
    cmd: curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.rpm.sh" | bash
    creates: "/etc/yum.repos.d/runner_gitlab-runner.repo"

- name: Install GitLab Runner
  ansible.builtin.yum:
    name: gitlab-runner
    state: present
