---
- name: Download helm
  ansible.builtin.get_url:
    url: "https://get.helm.sh/helm-v4.0.4-linux-amd64.tar.gz"
    dest: "/tmp/helm.tar.gz"
    mode: "0644"

- name: Extract helm
  ansible.builtin.unarchive:
    src: "/tmp/helm.tar.gz"
    dest: "/tmp"
    remote_src: yes

- name: Install helm
  ansible.builtin.copy:
    src: "/tmp/linux-amd64/helm"
    dest: "/usr/local/bin/helm"
    mode: "0755"
    remote_src: yes
