---
- name: Download kubectl
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/v1.35.0/bin/linux/amd64/kubectl"
    dest: "/tmp/kubectl"
    mode: "{{ bin_perms }}"

- name: Install kubectl
  ansible.builtin.command:
    cmd: install -o root -g root -m 0755 /tmp/kubectl /usr/local/bin/kubectl
    creates: "/usr/local/bin/kubectl"
