---
- name: Install RHEL and Python packages
  ansible.builtin.include_tasks: rhel_packages.yaml

- name: Install Docker
  ansible.builtin.include_tasks: docker.yaml

- name: Install Helm
  ansible.builtin.include_tasks: helm.yaml

- name: Install kubectl
  ansible.builtin.include_tasks: kubectl.yaml

- name: Install kubesec
  ansible.builtin.include_tasks: kubesec.yaml

- name: Install AWS CLI
  ansible.builtin.include_tasks: aws_cli.yaml

- name: Install Trivy
  ansible.builtin.include_tasks: trivy.yaml

- name: Install Terraform
  ansible.builtin.include_tasks: terraform.yaml

- name: Install GitLab Runner
  ansible.builtin.include_tasks: gitlab_runner.yaml
