---
- name: Install yum-utils
  ansible.builtin.yum:
    name: yum-utils
    state: present

- name: Add HashiCorp repository
  ansible.builtin.command:
    cmd: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

- name: Install Terraform
  ansible.builtin.yum:
    name: terraform
    state: present
